
<?php
function customh5p_h5p_semantics_alter(&$semantics, $machine_name, $major_version, $minor_version) {
// Add subscript and superscript buttons to the text and advanced text editors.
  if ($machine_name == 'H5P.Text' OR $machine_name == 'H5P.AdvancedText') {
    $semantics[0]->tags[] = 'sub';
    $semantics[0]->tags[] = 'sup';
  }
// Turn the textfield input into an html field in the DragText module.
  if ($machine_name == 'H5P.DragText') {
        $semantics[1]->widget = 'html';
        $semantics[1]->enterMode = 'p';
}
}

// Embed a stylesheet into all h5p objects.
function customh5p_h5p_styles_alter(&$styles, $libraries, $mode) {
    $styles[] = (object) array(
      // Path relative to drupal root
      'path' => drupal_get_path('module', 'customh5p') . '/h5p-overrides.css',
      'version' => '?ver=1',
    );
}
// Add Google Analytics tracking to xAPI-enabled objects. 
function customh5p_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  $scripts[] = (object) array(
    // Path relative to drupal root
    'path' => drupal_get_path('module', 'customh5p') . '/h5p-ga.js',
    // Cache buster
    'version' => '?ver=0.0.1',
  );
}
